### ISSUE TITLE
Simple execution fails

### ISSUE THREAD

**Issue by zolotarovgl** [conchoecia/odp#24]
When trying to execute the simplest version of the pipeline, I get the following error:

```
snakemake -r -p --snakefile odp/scripts/odp -c1
None
Building DAG of jobs...
InputFunctionException in rule hmm_against_prots in file /home/grygoriyzolotarov/Documents/projects/odp_test/odp/scripts/odp, line 1825:
Error:
  IndexError: list index out of range
Wildcards:
  coloredby=BCnS_LGs
  sample=Mleiold
Traceback:
  File "/home/grygoriyzolotarov/Documents/projects/odp_test/odp/scripts/odp", line 1829, in <lambda>
```
I believe, it should be a mistake in the input lambda function:

```
rule hmm_against_prots:
    input:
        hmm = lambda wildcards: os.path.join(
            config["prot_to_color"][wildcards.coloredby],
            [x for x in list(os.listdir(
            config["prot_to_color"][wildcards.coloredby]))
                                      if x.endswith(".hmm")][0]),
        proteins = config["tool"] + "/db/{sample}_prots.pep"
```
My config looks like the following:

```
# this file is called config.yaml
ignore_autobreaks: True       # Skip steps to find breaks in synteny blocks
diamond_or_blastp: "diamond"  # "diamond" or "blastp"
plot_LGs: True                # Plot the ALGs based on the installed databases
plot_sp_sp: True              # Plot the synteny between two species, if False just generates .rbh files
species:
  A:
    proteins: data/A_long.pep.fasta # required field
    chrom:    data/A_long.chrom           # required field
    genome:   data/A_gDNA.fasta    # required field 


    minscafsize: 1000000 # optional field. Sets minimum scaffold size to plot. 

  B:
    proteins: data/B_long.pep.fasta
    chrom:    data/B_long.chrom
    genome:   data/B_gDNA.fasta
```
any ideas on what may be causing this error? Is there any way to just omit the coloring all together?

**Comment by conchoecia** [comment]
Thanks for trying the software, Grisha! It looks like you must have installed the software in the way intended (`cd odp && make`) because this rule that caused the error would not have appeared otherwise.

I tried to replicate this error and couldn't figure it out. To help me could you please tell me the result of `snakemake --version`?

I think the simplest solution for now is to do what I write below. 

Change to the directory where you've installed `odp` that has the `README.md`, `Makefile`, et cetera. Then:

```
mv LG_db LG_db_IGNORE
mkdir LG_db
```

Then go back and try to run the program again. This will force it to ignore all of the ALG datasets that are baked into the software. I am going to open another issue here to make this easier to toggle in the future. I see where I can improve the code (the `plot_LGs` flag is supposed to take care of this but is broken currently).

**Comment by conchoecia** [comment]
With [39eddc9](https://github.com/conchoecia/odp/commit/39eddc96baf34e60065e7d967fe7b8a1acf55dab), if you delete the software directory and re-pull the software, then it should work out of the box `plot_LGs: False` in the flags.

**Comment by conchoecia** [comment]
according to @zolotarovgl the error was fixed with a recent update. closing.
