### ISSUE TITLE
Error in analysis_D_and_FET / LG coloring

### ISSUE THREAD

**Issue by colinshew** [conchoecia/odp#55]
Hi, thanks for this great tool! I have been running into an issue recently in generating the species v. species dot plots.

```
Error in rule analysis_D_and_FET:
    jobid: 0
    input: odp/step1-rbh/Alucayanum_Bfloridae_reciprocal_best_hits.rbh, odp/step0-chromsize/analyses/Alucayanum_Bfloridae.chromsize
    output: odp/step1-rbh/Alucayanum_Bfloridae_reciprocal_best_hits.D.FET.rbh

RuleException:
KeyError in file odp/scripts/odp, line 676:
"Only a column name can be used for the key in a dtype mappings argument. 'color' not found in columns."
  File "odp/scripts/odp", line 1853, in __rule_analysis_D_and_FET
  File "odp/scripts/odp", line 676, in calculate_FET
  File "mambaforge/envs/of/lib/python3.11/site-packages/pandas/core/generic.py", line 6290, in astype
  File "mambaforge/envs/of/lib/python3.11/concurrent/futures/thread.py", line 58, in run
```

I think the `prot_to_color` variable in the snakefile is involved, since adding test values to the config file changes the error message and `coloredby` in rule `hmm_against_prots`. It looks like this is supposed to be a dictionary giving paths to the linkage group information in `odp/LG_db/`? I tried reconstructing it but can't get it to run; all the .hmm and .rbh files appear to be intact.  The plots in `ALG-species_plots` are also created as normal.

This used to work, so I tried reinstalling and am getting the same issue. Any idea what might be going wrong?

**Comment by conchoecia** [comment]
Hi - did you add something to, or modify the contents of, the LG_db directory? Did you manually change some files in the middle of a run? That is the only thing I can think of at the moment!

**Comment by conchoecia** [comment]
If you send me the complete run logs and these two files I will have a better chance of figuring it out. `    input: odp/step1-rbh/Alucayanum_Bfloridae_reciprocal_best_hits.rbh, odp/step0-chromsize/analyses/Alucayanum_Bfloridae.chromsize`

At the moment I don't have much time to devote to bug fixes, as I am the only developer. Thanks for being patient. :)

**Comment by arcosintan** [comment]
Thanks for your great tool !  I encountered the same problem. My python version is 3.11 and other packages are the newest( until 2023.10.23 ).

Warning Rule：
```
Error in rule analysis_D_and_FET:
    jobid: 0
    input: odp/step1-rbh/spe1_spe2_reciprocal_best_hits.rbh, odp/step0-chromsize/analyses/spe1_spe2.chromsize
    output: odp/step1-rbh/spe1_spe2_reciprocal_best_hits.D.FET.rbh
```

Warning File：
```
RuleException:
KeyError in file 
~/odp/scripts/odp, line 676:
"Only a column name can be used for the key in a dtype mappings argument. 'color' not found in columns."
  File "~/odp/scripts/odp", line 1853, in __rule_analysis_D_and_FET
  File "~/odp/scripts/odp", line 676, in calculate_FET
  File "/home/miniconda3/envs/odp/lib/python3.11/site-packages/pandas/core/generic.py", line 6498, in astype
  File "/home/miniconda3/envs/odp/lib/python3.11/concurrent/futures/thread.py", line 58, in run
```

In file “odp/scripts/odp", line 676, calculate_FET:
```
# set the types of the dataframe
    types = {"rbh"        : str,
             "gene_group" : str, # "color"      : str,
             "whole_FET"  : float,
             "break_FET"  : float}
    for colname in genesdf.columns:
        if colname.endswith("_gene"):
            types[colname] = str
        if colname.endswith("_scaf"):
            types[colname] = str
        elif colname.endswith("_pos"):
            types[colname] = int
        elif colname.endswith("_ix"):
            types[colname] = int
        elif colname.endswith("_break_ix"):
            types[colname] = int
        elif colname.endswith("_breakchrom"):
            types[colname] = object
    genesdf = genesdf.astype(types)
```
I annotated the color line. In this way, the function can exit normally, and there will be no error when it is referred to next. The program can run normally, but there are a few warnings.I guess that because the input file `odp/step1-rbh/spe1_spe2_reciprocal_best_hits.rbh`was generated without color column (different from .rbh with CLGs), an error occurred when reading due to missing fields.

Warning:
```
~/odp/scripts/odp_color_manager.py:306: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '#000000' has dtype incompatible with float64, please explicitly cast to a compat
  plotdf.loc[index,"color"] = color
~/odp/scripts/odp_color_manager.py:307: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'None' has dtype incompatible with float64, please explicitly cast to a compatibl
  plotdf.loc[index,"gene_group"] = group
```

I don't know the specific technical details and what impact it will have on subsequent analysis.At present, it is only found that the pdf identification color in the generated `odp/step2-figures/synteny_nocolor/` is all black (#000000), which corresponds to the color in `.rbh`.

Thanks again! Have a good time!  :)

**Comment by conchoecia** [comment]
I recently pushed an updated, https://github.com/conchoecia/odp/commit/ba6c45375c2bf5e75a9ff0779e5d75b5509209db, which may correct these issues. 

You are correct in that the files in `odp/step2-figures/synteny_nocolor/` will be all black. These are just pairwise comparisons without respect to known ALGs. The other folders that will be present if the database installation steps are followed will have colors, since they correspond to known ALGs. 

Closing for now, please reopen this if you have other questions, or a new question if something else comes up.
